from django.contrib import admin

from {{ appname }}.models import *

__author__  = 'ProtocolMapper by Simone Pandolfi'
__email__   = 'simopandolfi@gmail.com'
{% if version is defined %}
__version__ = {{ version }}
{% endif %}

""" This file was generated by ProtocolMapper
    Checkout the repo for more informations [https://github.com/simongsr/protocol_mapper]
"""


{% for model in env|core.models if ('python_django__builtin' not in model.modifiers and 'builtin' not in model.modifiers) or model.modifiers.python_django__builtin == False or model.modifiers.builtin == False %}
{% for field in model.fields.values() if field.id > 0 and field.multiplicity == 'repeated' and field.data_type is string %}
class {{ field|python_django.class_name }}Admin(admin.ModelAdmin):
    pass

admin.site.register({{ field|python_django.class_name }}, {{ field|python_django.class_name }}Admin)


{% endfor %}
class {{ model|python_django.class_name }}Admin(admin.ModelAdmin):
    pass

admin.site.register({{ model|python_django.class_name }}, {{ model|python_django.class_name }}Admin)


{% endfor %}

